#pragma once

// Assets Pengu ships inside core.dll and serves over `https://plugins/@pengu/`,
// ahead of the plugins directory.
//
// Today that is exactly one file: `views.js`, Pengu's own SolidJS UI. It used
// to be bundled into the preload IIFE and eval'd synchronously in
// OnContextCreated, which put ~89 kB on the critical path before any of LCUX's
// own scripts could run. Splitting it out drops the synchronous payload to
// ~11 kB; loader.ts pulls this in via dynamic import before plugins load.
//
// The `@pengu/` prefix is reserved — a plugin cannot shadow these, because the
// lookup happens before the plugins directory is consulted.
//
// Matched on the whole path rather than a hash. An earlier design keyed a map
// on fnv32 of the path with no post-hit verification, where a collision serves
// the wrong file silently. With a handful of entries a linear compare costs
// nothing and cannot be wrong.
//
// BROWSER PROCESS ONLY — included by assets.cc.

#include "pengu.h"
#include "include/capi/cef_stream_capi.h"

#include <string>

namespace assets
{
#ifndef _DEBUG
    // Byte array + size, generated by the `pengu-build` vite plugin.
    // Included inside the namespace so the symbols don't reach global scope.
#   include "../../packages/preload/dist/views.g.h"
#endif

    inline constexpr const char16_t *BUILTIN_VIEWS = u"/@pengu/views.js";

    ///
    /// Open a built-in asset by its request path — already URI-decoded and with
    /// the query stripped. Returns nullptr when the path is not one of ours, in
    /// which case the caller falls through to the plugins directory.
    ///
    /// The returned stream is owned by the caller.
    ///
    inline cef_stream_reader_t *builtin_stream(const std::u16string &request_path)
    {
        if (request_path != BUILTIN_VIEWS)
            return nullptr;

#ifndef _DEBUG
        return cef_stream_reader_create_for_data(
            (void *)_views_script, _views_script_size);
#else
        // Debug reads it off disk instead, so iterating on the UI needs only
        // `pnpm --filter @pengujs/preload build` — no core rebuild. Anchored on
        // __FILE__ for the same reason as the preload script in renderer.cc:
        // the DLL is deployed away from the source tree, so a module-relative
        // path finds nothing. Both build systems force an absolute __FILE__
        // (CMake /FC, vcxproj UseFullPaths).
        const path views = path{ __FILE__ }
            .parent_path()      // core/src/browser
            .parent_path()      // core/src
            .parent_path()      // core
            .parent_path()      // <repo>
            / "packages" / "preload" / "dist" / "views.js";

        if (!file::is_file(views))
            return nullptr;

        // Named local: the cef_string_t has to outlive the call.
        const std::u16string views_str = views.u16string();
        auto path_str = CefStr::wrap(views_str);
        return cef_stream_reader_create_for_file(&path_str);
#endif
    }
}
